# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 6c0cf79383e82ca10ffef16e4c454665802cd6ddcf82d68e176d6905c49e5ff20df9a1eef02eb06e9d6bb301add61b89d2ac31e7839cc4bee78d6909b4c070bf

test:
  domain_name: example.com 
  secret_key_base: b10c17d962a2d438165581cdea28c9ad90fc1a54f20bc95282a0b1c5a2f82df4c515a31f43e19a798554bdd93e159a8a73c3de3bf64b5b3cd51568b74f1de30e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
